stanzas:
    - type: webapp
      exec: ../hello
      args:
        - Hello World 2
      env:
        FROM_KETER_CONFIG: foo bar baz
      forward-env:
        - FROM_SYSTEM_ENV
        - ANOTHER_ENV_VAR
      hosts:
        - keter1_0
        - pong1_0

    - type: static-files
      host: foobar
      root: ..
      directory-listing: true
      requires-secure: true

    - type: static-files
      host: unsafe1_1_0
      root: ../../

    - type: static-files
      host: unsafe2_1_0
      root: /home
      middleware:
         - autohead
         - accept-override
         - jsonp
         - method-override
         - method-override-post
         - local:
             status : 405
             message: "Keter Rocks localy"
         - basic-auth:
              realm: "bla bla"
              creds:
                 jon : rocks
                 bla : dada
         - headers:
             Access-Control-Allow-Origin : "*"
    - type: reverse-proxy
      reversed-host: www.yesodweb.com
      reversed-port: 80
      reversing-host: localhost

postgres: true

plugins:
    #postgres: true
